### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Bravelemming**
commit example to show forking and pull requests

You can also add a message here before you finish the pull request.

### CODE REVIEW

**Comment by Bravelemming** [comment]
Hey just noticed this request hadn't been seen yet! (example)

**Comment by silasfelinus** [comment]
I like it. It's succinct

**Comment by silasfelinus** [comment]
But is it TOO succinct?

**Review by Bravelemming — COMMENTED** [review]
looks good!

**Pull request merged**
